BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Tarefa" (
	"IdText"	INTEGER NOT NULL,
	"Texto"	TEXT NOT NULL UNIQUE,
	"Concluido"	INTEGER NOT NULL,
	"Data (TimeStamp)"	TEXT NOT NULL,
	PRIMARY KEY("IdText" AUTOINCREMENT)
);
COMMIT;
